from sqlalchemy import Column, String, Integer, Float, DateTime, Select
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class MasterBond(Base): 
    __tablename__ = 'Master' 
    Issuer = Column(String)    
    Ticker = Column(String)
    Coupon = Column(Float)
    Maturity = Column(DateTime)
    IssueDate = Column(DateTime)
    ISIN = Column(String, primary_key=True)
    PreferredRIC = Column(String)
    PrincipalCurrency = Column(String)
    CountryofIssue = Column(String)
    IssuerType = Column(String)
    InstrumentType = Column(String)
    CouponType = Column(String)
    BondGrade = Column(String)
    Sector = Column(String)
    GreenBond = Column(String)
    Putable = Column(String)
    Callable = Column(String)
    HasSinkingFund = Column(String)
    CouponFrequency = Column(Float)
    CapitalTier = Column(Float)
    IsCallable = Column(String)
    IsPutable = Column(String)
    SeniorityType = Column(String)
    SeniorityTypeShortDescription = Column(String)
    SIC = Column(Float)
    GuarantorType = Column(String)
    OptionAdjustedSpread = Column(Float)
    BidAskSpread = Column(Float)
    TypeofSinkingFund = Column(Float)
    NegativePledgeFlag = Column(String)
    DebtIncurrenceLimitationFlag = Column(String)
    CrossDefaultFlag = Column(String)
    ChangeOfControlPutFlag = Column(String)
    SaleOfAssetsFlag = Column(String)
    AffiliateTransactionsFlag = Column(String)
    MergerFlag = Column(String)
    SaleLeasebackFlag = Column(String)
    CollectiveActionClausesFlag = Column(Float)
    ForceMajeureFlag = Column(String)
    DefaultEventsFlag = Column(String)
    KeepwellAgreementFlag = Column(Float)
    PariPassuFlag = Column(String)
    GreenBondFlag = Column(String)
    FirstCouponDate = Column(String)
    MaturityYearsToRedem = Column(Float)
    DayCount = Column(String)
    AssetStatus = Column(String)
    AssetStatusDescription = Column(String)

class PricesSpreads(Base):  # Replace 'NewTable' with the actual table name
    __tablename__ = 'Prices'  # Replace 'new_table' with the actual table name
    
    Date = Column(String)
    Bid = Column(Float)
    Ask = Column(Float)
    BidYld = Column(Float)
    AskYld = Column(Float)
    BidYChg = Column(Float)
    Calculated_DirtyPrice = Column(Float)
    ZSpread = Column(Float)
    Calculated_ZSpread = Column(Float)
    RedemptionDate = Column(String)
    ID = Column(String)
    ISIN = Column(String, primary_key=True)
